### ISSUE TITLE
Compile issue from new version

### ISSUE THREAD

**Issue by tcosentino** [draft-js-plugins/find-with-regex#4]
I think this was caused by the 1.1.2 release 30 mins ago or so, but I am seeing this now when building/running tests:

```
/home/ubuntu/Contuit-WebApp/node_modules/find-with-regex/build/index.js:17
    export default findWithRegex;
    ^^^^^^
    SyntaxError: Unexpected token export
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/draft-js-mention-plugin/lib/mentionSuggestionsStrategy.js:7:22)
      at Object.<anonymous> (node_modules/draft-js-mention-plugin/lib/index.js:41:35)
```

I found a workaround [here](https://github.com/SebastianM/angular-google-maps/issues/1052#issuecomment-331150772) where I can compile after npm install and that is working for me currently.

**Comment by 9still** [comment]
The problem was caused by the following change: https://github.com/draft-js-plugins/find-with-regex/commit/23eb5de85b4f63dad2df3354db7c64d26caca514#diff-e56633f72ecc521128b3db6586074d2cR6, which switched from commonjs export format to native ES6 (see https://babeljs.io/docs/plugins/preset-env/#modules)    

This is breaking our build as well, could you guys remove the `modules` setting, or explicitly change it to `commonjs`?

@juliankrispel @nikgraf

**Comment by juliankrispel** [comment]
@gmatroskin @tcosentino crap! Sorry about that. Just fixed and pushed to npm - try again please :) it's commonjs now.
